//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamManage_Entities : DbContext
    {
        public TeamManage_Entities()
            : base("name=TeamManage_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BreakOff> BreakOffs { get; set; }
        public DbSet<DailyProjectReport> DailyProjectReports { get; set; }
        public DbSet<DailyReport> DailyReports { get; set; }
        public DbSet<OverTime> OverTimes { get; set; }
        public DbSet<QA_Files> QA_Files { get; set; }
        public DbSet<QA_Request> QA_Request { get; set; }
        public DbSet<QA_Test> QA_Test { get; set; }
        public DbSet<QA_TestIssue> QA_TestIssue { get; set; }
        public DbSet<t_ABAttach> t_ABAttach { get; set; }
        public DbSet<t_AlertBase> t_AlertBase { get; set; }
        public DbSet<t_AlertUser> t_AlertUser { get; set; }
        public DbSet<t_AUAttach> t_AUAttach { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<TraineeAttendance> TraineeAttendances { get; set; }
        public DbSet<TraineeBreakOff> TraineeBreakOffs { get; set; }
        public DbSet<UploadFile> UploadFiles { get; set; }
        public DbSet<UserAppraisal> UserAppraisals { get; set; }
        public DbSet<UserLeave> UserLeaves { get; set; }
        public DbSet<UserLeaveCutLog> UserLeaveCutLogs { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<UserToken> UserTokens { get; set; }
        public DbSet<VoteDetail> VoteDetails { get; set; }
        public DbSet<VoteItem> VoteItems { get; set; }
        public DbSet<VoteProject> VoteProjects { get; set; }
    }
}
