//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_Files
    {
        public QA_Files()
        {
            this.QA_Request = new HashSet<QA_Request>();
            this.QA_Test = new HashSet<QA_Test>();
            this.QA_TestIssue = new HashSet<QA_TestIssue>();
        }
    
        public System.Guid FileID { get; set; }
        public string Name { get; set; }
        public byte[] FileContent { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<QA_Request> QA_Request { get; set; }
        public virtual ICollection<QA_Test> QA_Test { get; set; }
        public virtual ICollection<QA_TestIssue> QA_TestIssue { get; set; }
    }
}
