//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_Request
    {
        public QA_Request()
        {
            this.QA_Test = new HashSet<QA_Test>();
            this.QA_Files = new HashSet<QA_Files>();
        }
    
        public System.Guid RequestID { get; set; }
        public string Project { get; set; }
        public string RelatedJIRA { get; set; }
        public string Developer { get; set; }
        public string Instruction { get; set; }
        public string Comments { get; set; }
        public string Fields { get; set; }
        public string Log { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual QA_Request QA_Request1 { get; set; }
        public virtual QA_Request QA_Request2 { get; set; }
        public virtual ICollection<QA_Test> QA_Test { get; set; }
        public virtual ICollection<QA_Files> QA_Files { get; set; }
    }
}
