//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_TestIssue
    {
        public QA_TestIssue()
        {
            this.QA_Files = new HashSet<QA_Files>();
        }
    
        public System.Guid TestIssueID { get; set; }
        public System.Guid TestReportID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Log { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<QA_Files> QA_Files { get; set; }
    }
}
