//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_TestIssue
    {
        public QA_TestIssue()
        {
            this.QA_Files = new HashSet<QA_Files>();
        }
    
        public System.Guid TestIssueID { get; set; }
        public System.Guid TestReportID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Log { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<QA_Files> QA_Files { get; set; }
    }
}
