//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_AlertUser
    {
        public t_AlertUser()
        {
            this.t_AUAttach = new HashSet<t_AUAttach>();
        }
    
        public int AUID { get; set; }
        public string UserID { get; set; }
        public string CcUser { get; set; }
        public int ABID { get; set; }
        public string AUTitle { get; set; }
        public string AUContent { get; set; }
        public Nullable<int> AUType { get; set; }
        public Nullable<int> AUStatus { get; set; }
        public int AUInterval { get; set; }
        public int AUUnitNum { get; set; }
        public System.DateTime AUTime { get; set; }
        public string AURemark { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual t_AlertBase t_AlertBase { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<t_AUAttach> t_AUAttach { get; set; }
    }
}
