//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_AlertBase
    {
        public t_AlertBase()
        {
            this.t_AlertUser = new HashSet<t_AlertUser>();
        }
    
        public int ABID { get; set; }
        public string ABName { get; set; }
        public Nullable<int> ABType { get; set; }
        public Nullable<int> ABStatus { get; set; }
        public Nullable<int> ABOrder { get; set; }
        public string ABRemark { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<t_AlertUser> t_AlertUser { get; set; }
    }
}
