//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public string UserID { get; set; }
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string GroupName { get; set; }
    }
}
