//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeave
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int AnnualDays { get; set; }
        public int AnnualDaysRest { get; set; }
        public int OverTime { get; set; }
        public int OverTimeRest { get; set; }
        public Nullable<System.DateTime> InitDateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> AnnualDaysERP { get; set; }
    }
}
