//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppraisal
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> WorkDone { get; set; }
        public Nullable<decimal> BugCreated { get; set; }
        public Nullable<decimal> WorkQuality { get; set; }
        public Nullable<decimal> DailyPerformance { get; set; }
        public System.DateTime DateTime { get; set; }
        public string GroupName { get; set; }
    }
}
