//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeaveCutLog
    {
        public int ID { get; set; }
        public System.Guid BreakOFFID { get; set; }
        public string UserID { get; set; }
        public string LeaveType { get; set; }
        public int CutHour { get; set; }
        public System.DateTime CutDateTime { get; set; }
    }
}
