//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManager.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppraisal
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> WorkDone { get; set; }
        public Nullable<decimal> BugCreated { get; set; }
        public Nullable<decimal> WorkQuality { get; set; }
        public Nullable<decimal> DailyPerformance { get; set; }
        public System.DateTime DateTime { get; set; }
        public string GroupName { get; set; }
    }
}
